#!/bin/bash
echo "Building Terraform container..."
(cd terraform && docker build . -t terraform -q)
#echo "Building Ansible container..."
#(cd ansible && docker build . -t ansible -q)
echo "Sucessfully built"
