#!/bin/bash

source bash/ansible.sh
source bash/terraform.sh
source bash/ui.sh

build_containers() {
    if [ "$build" == "terraform" ]; then
        build_terraform
    elif [ "$build" == "ansible" ]; then
        build_ansible
    elif [ "$build" == "all" ]; then
        build_terraform
        build_ansible
    fi
}

run_containers() {
    if [ "$run" == "terraform" ]; then
        run_terraform
    elif [ "$run" == "ansible" ]; then
        list_tags
        list_hosts
        run_ansible
    elif [ "$run" == "all" ]; then
        run_terraform
        list_tags
        list_hosts
        run_ansible
    fi
}

main() {
    check_for_gum
    check_for_jq
    select_build
    build_containers
    select_run
    run_containers
}

main
